name: book_list
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  get_it: ^7.7.0

  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.1
  shimmer: ^3.0.0

  easy_localization: ^3.0.7


  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/icons/
#    - assets/languages/
#    - assets/fonts/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
